name: Download Pause Image

on:
  workflow_dispatch: # 只允许手动触发

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Pull, save, and upload pause image
        run: |
          docker pull rancher/mirrored-pause:3.6
          docker save rancher/mirrored-pause:3.6 -o pause.tar
      - name: Upload pause image artifact
        uses: actions/upload-artifact@v4
        with:
          name: pause-image-tar
          path: pause.tar
